name: Update JSON from Excel

on:
  push:
    branches:
      - main  # Esegui lo script ogni volta che c'Ã¨ un push su "main"

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: ğŸ“¦ Install Dependencies
        run: pip install pandas openpyxl
      
      - name: ğŸ—‘ï¸ Rimuovi table.json
        run: rm -f files/table.json 

      - name: ğŸ—‘ï¸ Rimuovi vix.json
        run: rm -f files/vix.json 
      
      - name: ğŸ—‘ï¸ Rimuovi sp.json
        run: rm -f files/sp.json 
        

      - name: ğŸš€ Run Script
        run: python script.py
      
      - name: â³ Attendi 2 minuti prima del commit
        run: sleep 180  

      - name: ğŸ”„ Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add files/table.json
          git add files/vix.json
          git add files/sp.json
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Aggiornato files json da Excel"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          )